language: java

jdk:
  - openjdk11

os:
  - linux

before_install:
  - chmod +x springboot/gradlew

cache:
  directories:
    - $HOME/.gradle

script:
  - cd springboot
  - .gradlew clean test -Penvironment=dev
