language: java

jdk:
  - openjdk11

os:
  - linux

before_install:
  - chmod +x springboot/gradlew

cache:
  directories:
    - $HOME/springboot/.gradle

before_script:
  - cd springboot

script:
  - ./gradlew clean test
