version: '3'

services:

  minio:
    image: "minio/minio"
    environment:
      MINIO_ACCESS_KEY: 8JSB0V0DMKSVMH1AT0ON
      MINIO_SECRET_KEY: UJuDxruBKDjYKyUPkpIFUgAS9EDlOyH5B4IueJKd
    ports:
    - "9001:9000"
    volumes:
    - ./volumes/minio-data:/export
    command: minio server /export
    networks:
    - springboot

networks:

  springboot:
    driver: bridge
