###############################################################################################
#                                      Application                                            #
###############################################################################################
server.port: 8090

###############################################################################################
#                                      Monitoring                                            #
###############################################################################################

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  boot.admin.client.url: http://localhost:10000
  ###############################################################################################
  #                                      Devtools                                               #
  ###############################################################################################
  devtools:
    restart:
      enabled: true     # true is default
    livereload:
      enabled: true     # true is default
