###############################################################################################
#                                      Application                                            #
###############################################################################################
spring:
  application:
    name: Minio sample application
