###############################################################################################
#                                      Application                                            #
###############################################################################################
server.port: 8090

###############################################################################################
#                                      Monitoring                                            #
###############################################################################################

management:
  endpoints:
    web:
      exposure:
        include: '*'
